### ISSUE TITLE
night update

### ISSUE THREAD

**Issue by smileysit** [diddipoeler/sportsmanagement#342] opened 2016-08-14 08:26 UTC
were can i download the latest release or nightly update.
what is the best method of updated?
can i import players name, team, win, loss,percentage, competition, season,year?

**Comment by teddyfresco** [comment] 2016-08-15 00:24
Hi smileysit, please use this link
https://github.com/diddipoeler/sportsmanagement/archive/master.zip
to install (choose install from url in joomla admin) the last update
 and please use this forum
http://www.fussballineuropa.de/index.php?option=com_kunena&view=home&defaultmenu=144&Itemid=142
to ask things like this one.
You can import data from old joomleague files and other formats.
Now please close this issue, it is not a bug.

**Closed** 2016-08-16 09:12 UTC
